import type { Metadata } from "next";

import React from "react";

import { Urbanist } from "next/font/google";

import "@/shared/styles/index.css";

import "../styles";

const urbanistSans = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanistSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
