import type { Metadata } from "next";

import React from "react";

import { Urbanist } from "next/font/google";

import { HomeHeader } from "@/pages/home/components/HomeHeader/ui";
import "@/shared/styles/index.css";
import { Menu } from "@/shared/ui/Menu/ui";

import "../styles";

const urbanistSans = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanistSans.variable} antialiased`}>
        <HomeHeader className="my-16" />
        {children}
        <Menu />
      </body>
    </html>
  );
}
